parameters:
    publero_apple_mobile.store_receipt.factory.class: Publero\AppleMobileBundle\Factory\StoreReceiptFactory
    publero_apple_mobile.store_receipt.verifier.class: Publero\AppleMobileBundle\ReceiptVerifier\ReceiptVerifier
    publero_apple_mobile.store_receipt.manager.class: Publero\AppleMobileBundle\Entity\StoreReceiptManager

services:
    publero_apple_mobile.store_receipt.factory:
        class: %publero_apple_mobile.store_receipt.factory.class%
        public: false
        arguments: [%publero_apple_mobile.store_receipt_class%]

    publero_apple_mobile.store_receipt.verifier:
        class: %publero_apple_mobile.store_receipt.verifier.class%
        arguments: [%publero_apple_mobile.verification_url%]
        calls:
            - [ setStoreReceiptFactory, [ @publero_apple_mobile.store_receipt.factory ] ]

    publero_apple_mobile.store_receipt.manager:
        class: %publero_apple_mobile.store_receipt.manager.class%
        calls:
            - [ setStoreReceiptFactory, [ @publero_apple_mobile.store_receipt.factory ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
